title: tunjos.co
description: Tunjos Blog
author: tunjos
author_name: Tunji Olu-Taiwo
logo: https://tunjos.co/static/img/headshot1.jpg
github: https://github.com/tunjos
about: Happiness Engineer..Critical Thinker.
disqus_shortname:
google_analytics:
plain_url: tunjos.co
plain_url2: tunjos.com
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-info
    - text: Learn
      url: 'https://learn.tunjos.co'
      icon: fa-book
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Tinypoke
      url: 'https://tinypoke.co'
      icon: fa-building-o
      target: _blank
    - text: Happydrip
      url: 'https://www.happydrip.com'
      icon: fa-smile-o
      target: _blank
    - text: Github
      url: https://github.com/tunjos
      icon: fa-github
      target: _blank
    - text: Resume
      url: '/assets/tunji_olu-taiwo_resume.pdf'
      icon: fa-file-pdf-o
    - text: CV
      url: '/assets/tunji_olu-taiwo_resume.pdf'
      icon: fa-file-pdf-o
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      target: _blank

social:
    - icon: fa-twitter
      link: 'https://twitter.com/tunjos'
    - icon: fa-github
      link: 'https://github.com/tunjos'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/tunjos'
    - icon: fa-instagram
      link: 'https://www.instagram.com/tunjos.co'
    - icon: fa-envelope
      link: 'mailto:tunjos@tunjos.co'
    - links:
      - https://twitter.com/tunjos
      - https://github.com/tunjos
      - https://www.linkedin.com/in/tunjos
#      -https://stackexchange.com/users/000000/abcdef

share:
  twitter_username: tunjos
  fb_appid: 000000000000


enableTags: true
tagarray: []

#url: "http://localhost:4000"
url: "https://tunjos.co"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
permalink: /blog/:title/
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude: [_drafts/help]

#jekyll-seo-tag
twitter:
  username: tunjos
  card: summary
lang: en_GB

include: [".well-known"]